---
name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOSTNAME }}
          port: 22
          local_path: ./dist/*
          remote_path: /public_html
          sftp_only: true
          password: ${{ secrets.PASSWORD }}
